# Generated by Django 5.2.9 on 2026-01-17 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_alter_address_city_alter_address_line1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(default='Kollam', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='line1',
            field=models.CharField(default='vallikavu', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='address',
            name='postal_code',
            field=models.CharField(default='690525', max_length=20),
            preserve_default=False,
        ),
    ]
