# Generated by Django 5.2.9 on 2026-04-08 04:31

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bannerimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='banner_image/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='cosmetics',
            name='image',
            field=models.ImageField(upload_to='cosmetics_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='courses',
            name='image',
            field=models.ImageField(upload_to='courses/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='foodmenu',
            name='image',
            field=models.ImageField(upload_to='food_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image',
            field=models.ImageField(upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image1',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image2',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image3',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image4',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image5',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
        migrations.AlterField(
            model_name='saloon',
            name='image6',
            field=models.ImageField(blank=True, null=True, upload_to='saloon_images/', validators=[app.models.validate_image_size]),
        ),
    ]
