# Generated by Django 5.2.9 on 2026-07-29 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_eventhall_alter_product_image1_alter_product_image2_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventhall',
            name='status',
        ),
    ]
