# Generated by Django 5.2 on 2026-08-05 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_eventhall_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='FranchiseEnquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('mobile_number', models.CharField(max_length=20)),
                ('whatsapp_number', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('age_group', models.CharField(max_length=50)),
                ('current_city_district', models.CharField(max_length=200)),
                ('state', models.CharField(max_length=100)),
                ('occupation', models.CharField(max_length=200)),
                ('has_business_exp', models.CharField(max_length=20)),
                ('business_exp_details', models.TextField(blank=True, null=True)),
                ('has_salon_exp', models.CharField(max_length=20)),
                ('applicant_type', models.CharField(max_length=100)),
                ('preferred_city', models.CharField(max_length=100)),
                ('preferred_area', models.CharField(max_length=150)),
                ('has_commercial_property', models.CharField(max_length=100)),
                ('property_size', models.CharField(blank=True, max_length=100, null=True)),
                ('property_location_link', models.CharField(blank=True, max_length=500, null=True)),
                ('investment_budget', models.CharField(max_length=100)),
                ('investment_source', models.CharField(max_length=100)),
                ('plan_to_start', models.CharField(max_length=100)),
                ('daily_operations_involvement', models.CharField(max_length=100)),
                ('confirm_accurate', models.BooleanField(default=True)),
                ('agree_contact', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Franchise Enquiry',
                'verbose_name_plural': 'Franchise Enquiries',
                'ordering': ['-created_at'],
            },
        ),
    ]
